### ISSUE TITLE
Getting rhea::internal_error("objective function is unbounded.") on removing constraint.

### ISSUE THREAD

**Issue by har-gup** [Nocte-/rhea#49]
Reproducible sample: https://github.com/har-gup/rhea-issue

**Comment by Nocte-** [comment]
Thanks for the elaborate bug report! Unfortunately, I can't reproduce the bug on Linux. Right now I don't have access to a Windows machine, but I can probably give it a whirl after the weekend.

**Comment by har-gup** [comment]
Were you able to look now?

**Comment by Nocte-** [comment]
Yes, and I've been able to reproduce it, but haven't been able to figure out what is causing this.

**Comment by har-gup** [comment]
The remove_constraint method is supposed to remove the markers from the objective of the optimization. However, it removes them by just substracting the marker coefficient out of the objective.

While removing, the numbers seems to be very close to each other but not exactly the same and definitely with an error bigger than what rhea expects with its near_zero function 10e-8.

The coefficients are pretty large numbers that are multiplied and divided multiple times, because of all the calculus on the numbers, the value seems to change considerably

The difference in the error scenario was under 0.001 but not under 10e-8. And hence the error.

The error usually shows up when the multiplier in the constraint is 1/3. In those cases the computation of the strengths ends up being divided by 3 and later on multiplied back by 3, thus ending up having considerable amount of loss in precision.

Let me know if it helps.

**Comment by Nocte-** [comment]
That definitely helps. I completely missed that, good find!

Would it be possible for you to scale down the strengths by a factor 10? I think limiting everything to 1000 and setting the near_zero cutoff to 1e-6/-5 would improve the situation a lot already.

(That's lazy though. I should really try to come up with a more solid solution that doesn't accumulate rounding errors that easily.)

**Comment by har-gup** [comment]
Yeah... so as of now, I've just changed https://github.com/Nocte-/rhea/blob/0.3/rhea/simplex_solver.cpp#L531 to ignore the error if the entry variable's coefficient is between [0, -1]

I think your solution would also work.

But I'm curious what is the correct solution for this problem?

**Comment by Nocte-** [comment]
_what is the correct solution for this problem?_
libgmp 😂

The more I think about it, the more it seems this is unavoidable without some heavy bookkeeping overhead. Hopefully 21fd989 will make sure it's only a problem in seriously convoluted cases.
